version: '3.8'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - "DJANGO_SECRET_KEY=ytnf%@r@clw@()zx^rtw9tzf&bi%&5(0a_xa%v5ct7=#(+(t@b"
      - "DJANGO_DEBUG=True"

  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    ports:
    - 5432:5432

volumes:
  postgres_data: